//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspKurs.AplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaspEntities2 : DbContext
    {
        private static RaspEntities2 _context;

        public RaspEntities2()
            : base("name=RaspEntities2")
        {
        }
        public static RaspEntities2 GetContext() 
        {
            if (_context == null)
                _context = new RaspEntities2();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditorii> Auditorii { get; set; }
        public virtual DbSet<Para> Para { get; set; }
        public virtual DbSet<Prepod> Prepod { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Spec> Spec { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
    }
}
