//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspKurs.AplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Para
    {
        public int id_pari { get; set; }
        public int id_subject_pari { get; set; }
        public int id_auditor_pari { get; set; }
        public int id_prepod_pari { get; set; }
        public System.TimeSpan time_start { get; set; }
        public System.TimeSpan time_end { get; set; }
    
        public virtual Auditorii Auditorii { get; set; }
        public virtual Prepod Prepod { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
